### ISSUE TITLE
Unable to compile with igraph==0.10.2

### ISSUE THREAD

**Issue by atrostan** [ntamas/netctrl#6]
I am trying to compile netctrl using the latest version of igraph: 0.10.2

Unfortunately, the `cmake ..` command breaks. 
The errors shown all seem to be coming from the source code of the C++ interface that is initialized when I called: 
`git submodule update --init`.

Here is a list of unique errors raised:
```
/netctrl/vendor/igraphpp/include/igraph/cpp/str_vector.h:96:30: error: ‘igraph_strvector_t’ {aka ‘struct s_igraph_strvector’} has no member named ‘data’
   96 |         return m_pStrVector->data[size()-1];
```
```
/netctrl/vendor/igraphpp/include/igraph/cpp/str_vector.h:162:29: error: too many arguments to function ‘const char* igraph_strvector_get(const igraph_strvector_t*, igraph_integer_t)’
  162 |         igraph_strvector_get(m_pStrVector, idx, &result);
```
```
/netctrl/vendor/igraphpp/include/igraph/cpp/vector.h:54:59: error: cannot convert ‘igraph::Vector::pointer’ {aka ‘double*’} to ‘const igraph_vector_t*’
   54 |             IGRAPH_TRY(igraph_vector_init_copy(m_pVector, data, length));
      |                                                           ^~~~
      |                                                           |
      |                                                           igraph::Vector::pointer {aka double*}

```
```
/netctrl/vendor/igraphpp/include/igraph/cpp/vertex_selector.h:47:60: error: cannot convert ‘igraph_vector_t*’ to ‘const igraph_vector_int_t*’
   47 |         IGRAPH_TRY(igraph_vs_vector(&m_vs, vector->c_vector()));
      |                                            ~~~~~~~~~~~~~~~~^~
      |                                                            |
      |                                                            igraph_vector_t*
```

I tried to opt to use the precompiled binary, but the provided link is broken.
Any help would be appreciated!

**Comment by ntamas** [comment]
Thanks for the heads up and sorry about the late reply; I am not doing research any more and I haven't updated this project in a while and indeed it did not work with the latest version of igraph where the upstream API has changed a lot. I have now tried to bring it up-to-date so it now compiles and seems to provide sensible results for directed graphs.
